name: Docusaurus Deployment
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@master
        with:
          source-folder: .
          git-user: TheOriginalSoni
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages